#!/bin/sh

export LD_LIBRARY_PATH=@CMAKE_INSTALL_PREFIX@/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export PYTHONPATH=@PYTHON_PACKAGES_DIR@${PYTHONPATH:+:${PYTHONPATH}}

python @CMAKE_INSTALL_PREFIX@/bin/pyse.py $*
