#!/usr/bin/env python

import argparse
import monetdb
from os import path
import os

parser = argparse.ArgumentParser(description='Upgrade your TKP database.')
parser.add_argument('-d', '--database', help="what database to upgrade", default='trap', type=str)
parser.add_argument('-u', '--username', help="username for database", default='trap', type=str)
parser.add_argument('-p', '--password', help="password for database", default='trap', type=str)
parser.add_argument('-H', '--hostname', help="on what machine is the database running", default='localhost', type=str)
parser.add_argument('-P', '--port', help="on what port is the database running", default=50000, type=int)

def get_upgrades():
    location = path.join(path.dirname(__file__), 'sql/upgrade')
    files = [x for x in os.listdir(location) if x.endswith('.sql')]
    return [x[:-4].split('_to_') for x in files]

def get_version(cursor):
    cursor.execute("SELECT value FROM version WHERE name='revision'")
    return cursor.fetchall()[0][0]


def main():
    args = vars(parser.parse_args())
    database = args['database']
    username = args['username']
    password = args['password']
    hostname = args['hostname']
    port = args['port']

    connection = monetdb.sql.connect(database=database, username=username, password=password, hostname=hostname, port=port)
    cursor = connection.cursor()
    version = get_version(cursor)
    print version
    print get_upgrades()

if __name__ == "__main__":
    main()