DECLARE itheta, izoneheight DOUBLE;
DECLARE iimageid INT;
SET itheta = 0.025;
SET izoneheight = 1;
SET iimageid = 1;

SELECT t.BGfield
      ,t.xtrsrcid
      ,t.catname
      ,t.catsrcid
      ,t.assoc_distance_arcsec
  FROM (
SELECT -5 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra - alpha(5 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra - alpha(5 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra - alpha(5 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT -4 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra - alpha(4 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra - alpha(4 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra - alpha(4 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT -3 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra - alpha(3 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra - alpha(3 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra - alpha(3 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT -2 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra - alpha(2 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra - alpha(2 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra - alpha(2 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT -1 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra - alpha(1 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra - alpha(1 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra - alpha(1 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT 1 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra + alpha(1 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra + alpha(1 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra + alpha(1 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT 2 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra + alpha(2 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra + alpha(2 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra + alpha(2 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST(FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT 3 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra + alpha(3 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra + alpha(3 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra + alpha(3 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST( FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT 4 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra + alpha(4 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra + alpha(4 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra + alpha(4 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST( FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
UNION
SELECT 5 AS BGfield,x1.xtrsrcid,c.catname,c1.catsrcid,3600 * DEGREES(2 * ASIN(SQRT(POWER(c1.x - x1.x, 2) + POWER(c1.y - x1.y, 2) + POWER(c1.z - x1.z, 2)) / 2) ) AS assoc_distance_arcsec FROM (SELECT xtrsrcid AS xtrsrcid,ra + alpha(5 * (2 * itheta), decl) AS ra,decl AS decl,COS(RADIANS(decl)) * COS(RADIANS(ra + alpha(5 * (2 * itheta), decl))) AS x,COS(RADIANS(decl)) * SIN(RADIANS(ra + alpha(5 * (2 * itheta), decl))) AS y,z AS z FROM extractedsources xp1 WHERE image_id = iimageid) x1,catalogedsources c1,catalogs c WHERE c1.cat_id = c.catid AND c1.zone BETWEEN CAST( FLOOR((x1.decl - itheta) / izoneheight) AS INTEGER) AND CAST(FLOOR((x1.decl + itheta) / izoneheight) AS INTEGER) AND c1.ra BETWEEN x1.ra - alpha(itheta,x1.decl) AND x1.ra + alpha(itheta,x1.decl) AND c1.decl BETWEEN x1.decl - itheta AND x1.decl + itheta AND c1.x * x1.x + c1.y * x1.y + c1.z * x1.z > COS(RADIANS(itheta))
) t
ORDER BY t.BGfield
        ,t.xtrsrcid
;


