/**
 * This table collects the measurements.
 * A measurement is 
 * TODO: We do not know what the dataset format will
 * look like. For now we adopt HDF5
 */
CREATE TABLE measurements (
  msid BIGINT NOT NULL AUTO_INCREMENT,
  src_id INT NOT NULL,
  tau INT NOT NULL,
  taustart_timestamp BIGINT NOT NULL,
  ds_id INT NOT NULL,
  freqeff_id INT NOT NULL,
  ra_avg DOUBLE NOT NULL,
  decl_avg DOUBLE NOT NULL,
  ra_err_avg DOUBLE NOT NULL,
  decl_err_avg DOUBLE NOT NULL,
  I1 DOUBLE NULL,
  I1_err DOUBLE NULL,
  Q1 DOUBLE NULL,
  Q1_err DOUBLE NULL,
  U1 DOUBLE NULL,
  U1_err DOUBLE NULL,
  V1 DOUBLE NULL,
  V1_err DOUBLE NULL,
  I_n DOUBLE NULL,
  I_n_err DOUBLE NULL,
  Q_n DOUBLE NULL,
  Q_n_err DOUBLE NULL,
  U_n DOUBLE NULL,
  U_n_err DOUBLE NULL,
  V_n DOUBLE NULL,
  V_n_err DOUBLE NULL,
  I20 DOUBLE NULL,
  I20_err DOUBLE NULL,
  Q20 DOUBLE NULL,
  Q20_err DOUBLE NULL,
  U20 DOUBLE NULL,
  U20_err DOUBLE NULL,
  V20 DOUBLE NULL,
  V20_err DOUBLE NULL,
  I1_int DOUBLE NULL,
  I1_int_err DOUBLE NULL,
  Q1_int DOUBLE NULL,
  Q1_int_err DOUBLE NULL,
  U1_int DOUBLE NULL,
  U1_int_err DOUBLE NULL,
  V1_int DOUBLE NULL,
  V1_int_err DOUBLE NULL,
  I_n_int DOUBLE NULL,
  I_n_int_err DOUBLE NULL,
  Q_n_int DOUBLE NULL,
  Q_n_int_err DOUBLE NULL,
  U_n_int DOUBLE NULL,
  U_n_int_err DOUBLE NULL,
  V_n_int DOUBLE NULL,
  V_n_int_err DOUBLE NULL,
  I20_int DOUBLE NULL,
  I20_int_err DOUBLE NULL,
  Q20_int DOUBLE NULL,
  Q20_int_err DOUBLE NULL,
  U20_int DOUBLE NULL,
  U20_int_err DOUBLE NULL,
  V20_int DOUBLE NULL,
  V20_int_err DOUBLE NULL,
  PRIMARY KEY (msid),
  INDEX (src_id),
  FOREIGN KEY (src_id) REFERENCES sources(srcid),
  INDEX (freqeff_id),
  FOREIGN KEY (freqeff_id) REFERENCES effectivefrequency(freqeffid),
  INDEX (tau),
  INDEX (taustart_timestamp),
  INDEX (ds_id),
  FOREIGN KEY (ds_id) REFERENCES datasets(dsid)
) ENGINE=InnoDB;
