#! /bin/bash

# First part for argparse; second part for tkp_lib; third part for numpy, scipy & matplotlib. Edit as necessary
export PYTHONPATH=/home/evert/lofar/svn/tkp/code/pipe/python-packages

dir=`dirname $0`
${dir}/simlightcurve.py $@
result=$?

exit $result
