#!/bin/sh
# Input args: database (mysql/monetdb), writeToFile (true/false),
# Nimages, Nbands, Nbeams, Nsources (per image)

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 100 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 100 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 100 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1000 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1000 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 1000 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10000 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10000 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 ../databases/MonetDB/bin/MapiClient -lsql -umonetdb -Pmonetdb < ../databases/design/sql/create.pipelineMonetDBNoINDX.sql
 java org/lofar/pipeline/InsertPipelineArea monetdb64 true 10000 10 10 400 
done

