#!/bin/sh
# Nimages = 10, Nbands = 10, Nbeams = 10, Nsources (per image) = 10
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 10 10 10 10 
done

# Nimages = 10, Nbands = 10, Nbeams = 10, Nsources (per image) = 100
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 10 10 10 100 
done

# Nimages = 10, Nbands = 10, Nbeams = 10, Nsources (per image) = 1000
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 10 10 10 1000 
done

# Nimages = 100, Nbands = 10, Nbeams = 10, Nsources (per image) = 10
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 100 10 10 10 
done

# Nimages = 100, Nbands = 10, Nbeams = 10, Nsources (per image) = 100
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 100 10 10 100 
done

# Nimages = 100, Nbands = 10, Nbeams = 10, Nsources (per image) = 1000
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 100 10 10 1000 
done

# Nimages = 1000, Nbands = 10, Nbeams = 10, Nsources (per image) = 10
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 1000 10 10 10 
done

# Nimages = 1000, Nbands = 10, Nbeams = 10, Nsources (per image) = 100
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 1000 10 10 100 
done

# Nimages = 1000, Nbands = 10, Nbeams = 10, Nsources (per image) = 1000
for (( j = 0 ; j < 10; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea 1000 10 10 1000 
done

