#!/bin/sh
# Input args: database (mysql/monetdb), writeToFile (true/false),
# Nimages, Nbands, Nbeams, Nsources (per image)

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 100 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 100 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 100 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1000 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1000 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 1000 10 10 400 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10000 10 10 10 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10000 10 10 100 
done

for (( j = 0 ; j < 5; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10000 10 10 400 
done

