#!/bin/sh
# Input args: database (mysql/monetdb), writeToFile (true/false),
# Nimages, Nbands, Nbeams, Nsources (per image)

date
for (( j = 0 ; j < 1; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 java org/lofar/pipeline/InsertPipelineArea mysql true 1 10 10 10 
done
date

