#!/bin/sh
# Input args: database (mysql/monetdb), writeToFile (true/false),
# Nimages, Nbands, Nbeams, Nsources (per image)
date
for (( j = 0 ; j < 1; j++ ))
do
 echo "iter: `expr $j`"
 mysql -uroot < ../databases/design/sql/create.pipeline2InnoDB.sql
 date
 java org/lofar/pipeline/InsertMySQLPipelineArea mysql true 10000 10 10 400 
done
date
